"""Build docs/release_manifest.md from live repo state (hashes recomputed).

Run: python scripts/release/build_manifest.py. No test contact, no model
execution — file hashing and JSON reads only.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path


def sha(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for c in iter(lambda: f.read(1 << 20), b""):
            h.update(c)
    return h.hexdigest()


FILES = {
    "checkpoints": ["checkpoints/CLS-001/best.pt", "checkpoints/SEG-001/best.pt",
                    "checkpoints/ROB-001/best.pt"],
    "configs": ["configs/experiment/CLS-001.yaml", "configs/experiment/SEG-001.yaml",
                "configs/experiment/ROB-001.yaml", "configs/preprocessing/cls_baseline.yaml",
                "configs/preprocessing/seg_baseline.yaml",
                "configs/segmentation/localization.yaml",
                "configs/deployment/test_lock.yaml"],
    "data_manifest": ["outputs/data_gate_0/project_manifest.csv",
                      "outputs/data_gate_0/cross_split_exclusion_list.json"],
    "evidence": ["outputs/test_evaluation_7b860dca72ea.json",
                 "outputs/test_evaluation_7b860dca72ea_addendum_auc.json",
                 "outputs/CLS-001/calibration_frozen.json", "outputs/SEG-001/metrics.json",
                 "outputs/ROB-001/metrics.json", "outputs/ROB-001/locked_eval.json",
                 "outputs/UNC-001/unc001.json", "outputs/UNC-001/unc001_locked.json",
                 "outputs/PBA-003/pba003.json", "outputs/SYSINT/gpu_latency_fp32.json",
                 "outputs/SYSINT/fp16_check.json", "outputs/SYSINT/onnx_check.json",
                 "outputs/SYSINT/batchk8_check.json"],
    "contract_code": ["src/brain_tumor/contracts.py", "src/brain_tumor/inference/service.py",
                      "src/brain_tumor/preprocessing/pipeline.py", "app/api/main.py",
                      "app/streamlit/app.py"],
}


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    try:
        import torch
        runtime = f"torch {torch.__version__}"
    except ImportError:
        runtime = "torch not installed in this env"
    lines = ["# Release Manifest - Submission Baseline SB-1 (UTF-8)",
             "", "Generated by `scripts/release/build_manifest.py` (hashes recomputed).",
             f"Runtime here: {runtime}; python {sys.version.split()[0]}.", ""]
    missing = []
    for section, paths in FILES.items():
        lines.append(f"## {section}")
        for p in paths:
            fp = root / p
            if fp.is_file():
                lines.append(f"- `{p}` `{sha(fp)}` ({fp.stat().st_size} bytes)")
            else:
                lines.append(f"- `{p}` MISSING")
                missing.append(p)
        lines.append("")
    lines += ["## Status",
              "- SB-1 submission-ready fallback: CLS-001 + SEG-001 + UNC-001 "
              "(descriptive) + ROB-001 (documented variant) + FP16/autocast.",
              "- CPU CI: 49 passed (48 unit+integration + 1 data-gate; synthetic images only).",
              "- Locked evaluations closed; no tuning/re-cut permitted.",
              "- NOT included: optimizer-state `last.pt` files (remain on kernels), "
              "Kaggle HTML logs, tmp snapshots, `__pycache__`.",
              "- Claim boundary: measured BRISC-regime engineering results; "
              "not clinical diagnostic accuracy.", ""]
    (root / "docs" / "release_manifest.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"manifest written; missing={missing if missing else 'none'}")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
